Skip to content
KernelSU-Next_Actions-builder_Miatoll
Repository navigation
Code
Pull requests
Agents
Actions
Projects
Security and quality
Insights
Settings
Build Miatoll Hacking Kernel
Build Miatoll Hacking Kernel #33
All jobs
Run details
Annotations
1 error and 1 warning
Build Kernel for Miatoll
failed 2 minutes ago in 3m 11s
Search logs
0s
1s
0s
15s
1m 50s
49s
2s
0s
12s
Run cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
make[1]: Entering directory '/home/runner/work/KernelSU-Next_Actions-builder_Miatoll/KernelSU-Next_Actions-builder_Miatoll/kernel_workspace/android-kernel/out'
  HOSTCC  scripts/basic/fixdep
  GEN     ./Makefile
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
#
# configuration written to .config
#
make[1]: Leaving directory '/home/runner/work/KernelSU-Next_Actions-builder_Miatoll/KernelSU-Next_Actions-builder_Miatoll/kernel_workspace/android-kernel/out'
make[1]: Entering directory '/home/runner/work/KernelSU-Next_Actions-builder_Miatoll/KernelSU-Next_Actions-builder_Miatoll/kernel_workspace/android-kernel/out'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  GEN     ./Makefile
  WRAP    arch/arm64/include/generated/uapi/asm/errno.h
  CHK     include/generated/uapi/linux/version.h
  WRAP    arch/arm64/include/generated/uapi/asm/ioctl.h
  WRAP    arch/arm64/include/generated/uapi/asm/ioctls.h
  WRAP    arch/arm64/include/generated/uapi/asm/ipcbuf.h
  UPD     include/generated/uapi/linux/version.h
  WRAP    arch/arm64/include/generated/uapi/asm/kvm_para.h
  WRAP    arch/arm64/include/generated/uapi/asm/mman.h
  WRAP    arch/arm64/include/generated/uapi/asm/msgbuf.h
  WRAP    arch/arm64/include/generated/uapi/asm/poll.h
  WRAP    arch/arm64/include/generated/uapi/asm/resource.h
  WRAP    arch/arm64/include/generated/uapi/asm/sembuf.h
  WRAP    arch/arm64/include/generated/uapi/asm/shmbuf.h
  WRAP    arch/arm64/include/generated/uapi/asm/socket.h
  WRAP    arch/arm64/include/generated/uapi/asm/sockios.h
  WRAP    arch/arm64/include/generated/uapi/asm/swab.h
  WRAP    arch/arm64/include/generated/uapi/asm/termbits.h
  WRAP    arch/arm64/include/generated/uapi/asm/termios.h
  WRAP    arch/arm64/include/generated/uapi/asm/types.h
  HOSTCC  scripts/basic/fixdep
../net/Makefile:24: CC cannot link executables. Skipping bpfilter.
  UPD     include/config/kernel.release
  Using .. as source for kernel
  WRAP    arch/arm64/include/generated/asm/bugs.h
  WRAP    arch/arm64/include/generated/asm/clkdev.h
  WRAP    arch/arm64/include/generated/asm/delay.h
  WRAP    arch/arm64/include/generated/asm/div64.h
  WRAP    arch/arm64/include/generated/asm/dma.h
0s
0s
0s
0s
0s
